name:                punch
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tippenein/punch#readme
license:             BSD3
author:              Brady Ouren
maintainer:          tippenein@gmail.com
copyright:           2021 Brady Ouren
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - sqlite-simple
  - directory
  - filepath
  - optparse-generic
  - time

executables:
  punch:
    source-dirs:      src
    main:             Main.hs
